name: 'build' 
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
permissions:
  packages: write
jobs:
  list-images:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3
      - name: List image directories
        id: set-matrix
        run: echo "::set-output name=matrix::$(/bin/ls -1 -d */ | tr -d "/" | jq -R -s -c 'split("\n")[:-1]')"

  prebuild:
    needs: list-images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ${{ fromJson(needs.list-images.outputs.matrix) }}
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/sandor-juhasz/devcontainer-images/${{ matrix.image }}
          cacheFrom: ghcr.io/sandor-juhasz/devcontainer-images/${{ matrix.image }}
          push: always
          subFolder: ${{ matrix.image }}
